mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "latest"

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024
    resource:
      attributes:
        - key: deployment.environment
          value: "kubernetes"
          action: insert
        - key: cluster.name
          value: "proxmox-cluster"
          action: insert

  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
      namespace: "otel"
    debug:
      verbosity: detailed
    otlp/jaeger:
      endpoint: http://jaeger.tracing.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch, resource]
        exporters: [prometheus, debug]
      traces:
        receivers: [otlp]
        processors: [batch, resource]
        exporters: [debug, otlp/jaeger]

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
