# Prometheus configuration for monitoring namespace
fullnameOverride: "prometheus"

# Server configuration
server:
  enabled: true
  image:
    tag: "v2.50.1"

  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  # Service configuration
  service:
    type: ClusterIP
    port: 9090

  # Storage (using emptyDir for simplicity, use PV for production)
  persistentVolume:
    enabled: false

  # Configuration for scraping targets
  configMapOverrideName: "prometheus-config"

# AlertManager (optional, can disable if not needed)
alertmanager:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Node exporter to collect host metrics
nodeExporter:
  enabled: true

# Push gateway (optional)
pushgateway:
  enabled: false

# Kube state metrics for Kubernetes metrics
kubeStateMetrics:
  enabled: true

# Disable components you don't need
configmapReload:
  prometheus:
    enabled: true

# Custom scrape configurations
serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape OpenTelemetry Collector metrics
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector:8889']
        scrape_interval: 10s
        metrics_path: '/metrics'

      # Scrape Kubernetes API server
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      # Scrape node metrics
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
